---

- name: Verify
  hosts: node1
  gather_facts: false
  vars:
    rke2_data_path: /var/lib/rancher/rke2
  tasks:
    - name: Verify RKE2
      shell: |
        set -e
        set -o pipefail
        {{ rke2_data_path }}/bin/kubectl --kubeconfig /etc/rancher/rke2/rke2.yaml get nodes | grep " Ready" | wc -l
      args:
        executable: /bin/bash
      register: nodes

    - name: Check Nodes
      assert:
        that:
          - groups.all | length == nodes.stdout | int
        quiet: true

    - name: Get RKE2 config directory status
      stat:
        path: /etc/rancher/rke2
      register: rke2_config_dir

    - name: Check RKE2 config directory mode
      assert:
        that:
          - rke2_config_dir.stat.mode == "0750"
        quiet: true
